feat(zsh): zsh pgo
CachyOS/CachyOS-PKGBUILDS pull request #113
Opened 2024-01-06 12:21 UTC by lseman

zsh pgo, but we will wait until finally merging it;
I'm testing it on daily bassis as my main shell, we need to make sure nothing breaks on the user shell and it is 100% working.

2024-01-13 18:00 UTC, lseman commented
Is is working well, not a single problem.

2024-01-13 19:29 UTC, ventureoo approved these changes
LGTM

2024-01-18 20:20 UTC, vnepogodin requested changes

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +    export LIBS="-lgcov"
```suggestion
```

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +    cd ..
```suggestion
    HOME="${srcdir}" make check || true
```

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +    export CXXFLAGS="${CXXFLAGS} -fprofile-generate -fprofile-update=atomic -fprofile-partial-training"
```suggestion
    export CFLAGS="${CFLAGS} -fprofile-dir=${PROFILES_PGO_DIR} -fprofile-generate=${PROFILES_PGO_DIR} -fprofile-update=atomic -fprofile-partial-training"
    export CXXFLAGS="${CXXFLAGS} -fprofile-dir=${PROFILES_PGO_DIR} -fprofile-generate=${PROFILES_PGO_DIR} -fprofile-update=atomic -fprofile-partial-training"
```

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +    export CXXFLAGS="${CXXFLAGS} -fprofile-use -Wno-error=coverage-mismatch"
```suggestion
    export CFLAGS="${CFLAGS} -fprofile-dir=${PROFILES_PGO_DIR} -fprofile-use=${PROFILES_PGO_DIR} -Wno-error=coverage-mismatch"
    export CXXFLAGS="${CXXFLAGS} -fprofile-dir=${PROFILES_PGO_DIR} -fprofile-use=${PROFILES_PGO_DIR} -Wno-error=coverage-mismatch"
```

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +    unset LIBS
```suggestion
```

2024-01-18 20:20 UTC, vnepogodin commented on zsh/PKGBUILD
> +
```suggestion
    export PROFILES_PGO_DIR="$PWD/pgo-profiles"
    mkdir -p "${PROFILES_PGO_DIR}"
```

2024-02-03 20:45 UTC, merged