feat: Add zlib-ng
CachyOS/CachyOS-PKGBUILDS pull request #332
Opened 2024-09-02 13:34 UTC by 1Naim

We aim to replace zlib with zlib-ng to make use of the optimizations from the next generation implementation

Some benchmarks to highlight the benefits of this replacement:
- [zlib-ng - 2.0.0 Benchmark Discussions](https://github.com/zlib-ng/zlib-ng/discussions/871)
- [AWS - Comparisons between zlib-cloudflare, zlib-ng and other zlib forks](https://aws.amazon.com/blogs/opensource/improving-zlib-cloudflare-and-comparing-performance-with-other-zlib-forks/)
- [Megastorm's Systems zlib-ng vs zlib](https://www.megastormsystems.com/news/benchmarks-results-of-zlib-and-zlib-ng-running-on-some-amd-and-intel-cpus)

Closes #330

2024-09-02 16:42 UTC, ptr1337 commented
We also need to think about, how we do the integration.

e.g we would need to provide a replace=(zlib) for example, so that user will get when updating automatically the update. But for the testing right now that fits

2024-09-02 16:44 UTC, 1Naim commented
Currently `zlib-ng-compat` conflicts with `zlib` so for any users that currently build this manually they will get prompted.

It is true however that when we actually get down to merging this, we need to add that as an option.

2024-09-02 16:45 UTC, ptr1337 commented
We maybe want to add before the build part:
```
export CFLAGS+=" -fno-semantic-interposition"
export CXXLAGS+=" -fno-semantic-interposition"
```

2024-09-02 16:50 UTC, ptr1337 commented
Clearlinux uses following to PGO the package:
```
cat *.c | ./minigzip -6 | ./minigzip -d > /dev/null
cat *.c | ./minigzip -4 | ./minigzip -d > /dev/null
cat *.c | ./minigzip -9 | ./minigzip -d > /dev/null
cat minigzip | ./minigzip -6 | ./minigzip -d > /dev/null
cat minigzip | ./minigzip -4 | ./minigzip -d > /dev/null
cat minigzip | ./minigzip -9 | ./minigzip -d > /dev/null
```

Since mini(g)zip is provided by zlib. We could still run this as PGO profiling, due the compact package (likely). Needs to be tested.

Following C/CXX Flags should be used for profiling:
`-fprofile-generate -fprofile-update=atomic`
`-fprofile-use -fprofile-dir=$PGODIR -fprofile-correction`

2024-09-03 06:55 UTC, sirlucjan commented
Ive compiled and installed it - without any problem.

2024-09-06 13:17 UTC, 1Naim commented on zlib-ng/zlib-ng/PKGBUILD
> +  replaces=('zlib')
This need a bit more evaluation if we want to actually ship it to all users using our repo. 

There aren't any issues on my side so I'm +1 mostly.

2024-09-06 20:08 UTC, sirlucjan commented
I'm testing, using and it works.

2024-09-09 15:39 UTC, ptr1337 requested changes

2024-09-09 15:39 UTC, ptr1337 commented on zlib-ng/zlib-ng/PKGBUILD
> +	#   see https://github.com/gentoo/gentoo/pull/17167 for more info.
I think the formatting here is a bit failed

2024-09-09 15:47 UTC, ptr1337 approved these changes
So, lets merge this for now and put it into the cachyos-testing-v3 repository, and let some people test.

After that, we can try to push it to stable.

2024-09-09 15:47 UTC, merged